export const APPOINTMENT_TAB_OPTIONS = [
  {
    label: "Dashboard",
    index: 0,
    to: "/appointments/dashboard",
  },
  {
    label: "Appointments Calendar",
    index: 0,
    to: "/appointments/appointments_calendar",
  },
  {
    label: "All Appointments",
    index: 0,
    to: "/appointments/all_appointments",
  },
];

export const AllAppointemnts = {
  getAppointemnts() {
    return [
      {
        doctor: "Ulrich Akpodji",
        employeeId: "LZ-08",
        department: "Neurosurgery",
        image: "https://i.ibb.co/Qrt0TfS/Avatar-1.png",
        patientname: "Hamide Alici",
        dateandtime: "27 Oct 2022 11:02 AM",
        bookedvia: "App",
        status: "In Progress",
      },
      {
        doctor: "Ulrich Akpodji",
        employeeId: "LZ-08",
        department: "Neurosurgery",
        image: "https://i.ibb.co/Qrt0TfS/Avatar-1.png",
        patientname: "Hamide Alici",
        dateandtime: "27 Oct 2022 11:02 AM",
        bookedvia: "App",
        status: "In Progress",
      },
      {
        doctor: "Ulrich Akpodji",
        employeeId: "LZ-08",
        department: "Neurosurgery",
        image: "https://i.ibb.co/Qrt0TfS/Avatar-1.png",
        patientname: "Hamide Alici",
        dateandtime: "27 Oct 2022 11:02 AM",
        bookedvia: "App",
        status: "In Progress",
      },
      {
        doctor: "Ulrich Akpodji",
        employeeId: "LZ-08",
        department: "Neurosurgery",
        image: "https://i.ibb.co/Qrt0TfS/Avatar-1.png",
        patientname: "Hamide Alici",
        dateandtime: "27 Oct 2022 11:02 AM",
        bookedvia: "App",
        status: "In Progress",
      },
      {
        doctor: "Ulrich Akpodji",
        employeeId: "LZ-08",
        department: "Neurosurgery",
        image: "https://i.ibb.co/Qrt0TfS/Avatar-1.png",
        patientname: "Hamide Alici",
        dateandtime: "27 Oct 2022 11:02 AM",
        bookedvia: "App",
        status: "In Progress",
      },
      {
        doctor: "Ulrich Akpodji",
        employeeId: "LZ-08",
        department: "Neurosurgery",
        image: "https://i.ibb.co/Qrt0TfS/Avatar-1.png",
        patientname: "Hamide Alici",
        dateandtime: "27 Oct 2022 11:02 AM",
        bookedvia: "App",
        status: "In Progress",
      },
      {
        doctor: "Ulrich Akpodji",
        employeeId: "LZ-08",
        department: "Neurosurgery",
        image: "https://i.ibb.co/Qrt0TfS/Avatar-1.png",
        patientname: "Hamide Alici",
        dateandtime: "27 Oct 2022 11:02 AM",
        bookedvia: "App",
        status: "In Progress",
      },
      {
        doctor: "Ulrich Akpodji",
        employeeId: "LZ-08",
        department: "Neurosurgery",
        image: "https://i.ibb.co/Qrt0TfS/Avatar-1.png",
        patientname: "Hamide Alici",
        dateandtime: "27 Oct 2022 11:02 AM",
        bookedvia: "App",
        status: "In Progress",
      },
      {
        doctor: "Ulrich Akpodji",
        employeeId: "LZ-08",
        department: "Neurosurgery",
        image: "https://i.ibb.co/Qrt0TfS/Avatar-1.png",
        patientname: "Hamide Alici",
        dateandtime: "27 Oct 2022 11:02 AM",
        bookedvia: "App",
        status: "In Progress",
      },
      {
        doctor: "Ulrich Akpodji",
        employeeId: "LZ-08",
        department: "Neurosurgery",
        image: "https://i.ibb.co/Qrt0TfS/Avatar-1.png",
        patientname: "Hamide Alici",
        dateandtime: "27 Oct 2022 11:02 AM",
        bookedvia: "App",
        status: "In Progress",
      },
      {
        doctor: "Ulrich Akpodji",
        employeeId: "LZ-08",
        department: "Neurosurgery",
        image: "https://i.ibb.co/Qrt0TfS/Avatar-1.png",
        patientname: "Hamide Alici",
        dateandtime: "27 Oct 2022 11:02 AM",
        bookedvia: "App",
        status: "In Progress",
      },
    ];
  },

  getAllAppointemnts() {
    return Promise.resolve(this.getAppointemnts());
  },
};
